[project]
name = "smart-monitor"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "apscheduler>=3.11.2",
    "fastapi>=0.128.0",
    "psutil>=7.2.1",
    "tortoise-orm>=0.25.3",
    "uvicorn>=0.40.0",
]
